Repository ExpTechTW/CDPS, pull requests merged in 2024-06, with the labels that each got.

#1 feat: Dockerfile & github actions
  .github/workflows/github_actions.yml
  Dockerfile
Labels: size/M

#2 fix: docs
  docs/zh/developer/inject.md
Labels: size/XS

#3 fix: docs
  docs/zh/developer/inject.md
Labels: size/XS

#4 fix: docs
  docs/zh/developer/inject.md
Labels: size/XS

#5 fix: plugin dependencies crash
  cdps/plugin/manager.py
Labels: size/XS

#6 fix: plugin dependencies is None to remove
  cdps/plugin/manager.py
Labels: size/XS

#7 fix: check plugin dependencies
  cdps/plugin/manager.py
Labels: size/S

#8 fix: docs
  docs/zh/developer/inject.md
  docs/zh/user/plugins.md
Labels: size/XS

#10 feat: remove cdps file
  cdps/plugin/manager.py
Labels: size/XS

#11 Update plugins.md
  docs/zh/user/plugins.md
Labels: size/XS

#12 fix: completion event is None
  cdps/plugin/manager.py
Labels: size/XS

#9 feat: pip dependencies
  cdps/cdps_server.py
  cdps/plugin/manager.py
Labels: size/M

#13 style: plugin reduce
  cdps/cdps_server.py
  cdps/plugin/manager.py
Labels: size/M

#14 feat: cdps console plugin list
  cdps/console/cdps.py
Labels: size/XS
